# WSDL method definitions
require 'etapper/etapMappingRegistry'

module Etapper

  class MessagingService
    NsService = "etapestryAPI/service"

    Methods = [
      [ XSD::QName.new(NsService, "addAccount"),
        "",
        "addAccount",
        [ ["in", "Account_1", ["Etapper::Account", "etapestryAPI/service", "Account"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addAndProcessGift"),
        "",
        "addAndProcessGift",
        [ ["in", "Gift_1", ["Etapper::Gift", "etapestryAPI/service", "Gift"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addAndProcessPayment"),
        "",
        "addAndProcessPayment",
        [ ["in", "Payment_1", ["Etapper::Payment", "etapestryAPI/service", "Payment"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addContact"),
        "",
        "addContact",
        [ ["in", "Contact_1", ["Etapper::Contact", "etapestryAPI/service", "Contact"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addDisbursement"),
        "",
        "addDisbursement",
        [ ["in", "Disbursement_1", ["Etapper::Disbursement", "etapestryAPI/service", "Disbursement"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addGift"),
        "",
        "addGift",
        [ ["in", "Gift_1", ["Etapper::Gift", "etapestryAPI/service", "Gift"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addLoginCredentials"),
        "",
        "addLoginCredentials",
        [ ["in", "LoginCredentialsRequest_1", ["Etapper::LoginCredentialsRequest", "etapestryAPI/service", "LoginCredentialsRequest"]],
        ["retval", "result", ["Etapper::LoginCredentialsResponse", "etapestryAPI/service", "LoginCredentialsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addNote"),
        "",
        "addNote",
        [ ["in", "Note_1", ["Etapper::Note", "etapestryAPI/service", "Note"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addOutlookIntegrationEmail"),
        "",
        "addOutlookIntegrationEmail",
        [ ["in", "OutlookIntegrationEmail_1", ["Etapper::OutlookIntegrationEmail", "etapestryAPI/service", "OutlookIntegrationEmail"]],
        ["in", "arrayOfAccount_2", ["Etapper::ArrayOfAccount", "etapestryAPI/service", "ArrayOfAccount"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addOutlookIntegrationError"),
        "",
        "addOutlookIntegrationError",
        [ ["in", "String_1", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addOutlookIntegrationStats"),
        "",
        "addOutlookIntegrationStats",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "Date_2", ["::SOAP::SOAPDateTime"]],
        ["in", "int_3", ["::SOAP::SOAPInt"]],
        ["in", "int_4", ["::SOAP::SOAPInt"]],
        ["in", "int_5", ["::SOAP::SOAPInt"]],
        ["in", "int_6", ["::SOAP::SOAPInt"]],
        ["in", "int_7", ["::SOAP::SOAPInt"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addPayment"),
        "",
        "addPayment",
        [ ["in", "Payment_1", ["Etapper::Payment", "etapestryAPI/service", "Payment"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addPledge"),
        "",
        "addPledge",
        [ ["in", "Pledge_1", ["Etapper::Pledge", "etapestryAPI/service", "Pledge"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addRecurringGift"),
        "",
        "addRecurringGift",
        [ ["in", "RecurringGift_1", ["Etapper::RecurringGift", "etapestryAPI/service", "RecurringGift"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "addSoftCredit"),
        "",
        "addSoftCredit",
        [ ["in", "SoftCredit_1", ["Etapper::SoftCredit", "etapestryAPI/service", "SoftCredit"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "connect"),
        "",
        "connect",
        [ ["in", "ConnectRequest_1", ["Etapper::ConnectRequest", "etapestryAPI/service", "ConnectRequest"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "externalLogin"),
        "",
        "externalLogin",
        [ ["in", "ExternalLoginRequest_1", ["Etapper::ExternalLoginRequest", "etapestryAPI/service", "ExternalLoginRequest"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "findAccountsForOutlookIntegration"),
        "",
        "findAccountsForOutlookIntegration",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "String_2", ["::SOAP::SOAPString"]],
        ["in", "boolean_3", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfAccount", "etapestryAPI/service", "ArrayOfAccount"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getAccount"),
        "",
        "getAccount",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getAccountById"),
        "",
        "getAccountById",
        [ ["in", "int_1", ["::SOAP::SOAPInt"]],
        ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getAccountByPersonaType"),
        "",
        "getAccountByPersonaType",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "String_2", ["::SOAP::SOAPString"]],
        ["in", "boolean_3", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getAccountByUniqueDefinedValue"),
        "",
        "getAccountByUniqueDefinedValue",
        [ ["in", "DefinedValue_1", ["Etapper::DefinedValue", "etapestryAPI/service", "DefinedValue"]],
        ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getAccountFromPhoneAThonList"),
        "",
        "getAccountFromPhoneAThonList",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getAccountInvolvePrivacySettings"),
        "",
        "getAccountInvolvePrivacySettings",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getAccountRef"),
        "",
        "getAccountRef",
        [ ["in", "DefinedValue_1", ["Etapper::DefinedValue", "etapestryAPI/service", "DefinedValue"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getApproaches"),
        "",
        "getApproaches",
        [ ["in", "boolean_1", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfstring", "etapestryAPI/service", "ArrayOfstring"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCachedCartElements"),
        "",
        "getCachedCartElements",
        [ ["in", "int_1", ["::SOAP::SOAPInt"]],
        ["retval", "result", ["Etapper::PagedCartElementsResponse", "etapestryAPI/service", "PagedCartElementsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCachedDefinedFields"),
        "",
        "getCachedDefinedFields",
        [ ["in", "int_1", ["::SOAP::SOAPInt"]],
        ["retval", "result", ["Etapper::PagedDefinedFieldsResponse", "etapestryAPI/service", "PagedDefinedFieldsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCachedJournalEntries"),
        "",
        "getCachedJournalEntries",
        [ ["in", "int_1", ["::SOAP::SOAPInt"]],
        ["retval", "result", ["Etapper::PagedJournalEntriesResponse", "etapestryAPI/service", "PagedJournalEntriesResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCachedQueryResults"),
        "",
        "getCachedQueryResults",
        [ ["in", "int_1", ["::SOAP::SOAPInt"]],
        ["retval", "result", ["Etapper::PagedQueryResultsResponse", "etapestryAPI/service", "PagedQueryResultsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCalendarItem"),
        "",
        "getCalendarItem",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::CalendarItem", "etapestryAPI/service", "CalendarItem"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCampaigns"),
        "",
        "getCampaigns",
        [ ["in", "boolean_1", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfstring", "etapestryAPI/service", "ArrayOfstring"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCartCategory"),
        "",
        "getCartCategory",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::CartCategory", "etapestryAPI/service", "CartCategory"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCartElements"),
        "",
        "getCartElements",
        [ ["in", "PagedCartElementsRequest_1", ["Etapper::PagedCartElementsRequest", "etapestryAPI/service", "PagedCartElementsRequest"]],
        ["retval", "result", ["Etapper::PagedCartElementsResponse", "etapestryAPI/service", "PagedCartElementsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCartItem"),
        "",
        "getCartItem",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::CartItem", "etapestryAPI/service", "CartItem"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getCartPreferences"),
        "",
        "getCartPreferences",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::CartPreferences", "etapestryAPI/service", "CartPreferences"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getContact"),
        "",
        "getContact",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Contact", "etapestryAPI/service", "Contact"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getContactByUniqueDefinedValue"),
        "",
        "getContactByUniqueDefinedValue",
        [ ["in", "DefinedValue_1", ["Etapper::DefinedValue", "etapestryAPI/service", "DefinedValue"]],
        ["retval", "result", ["Etapper::Contact", "etapestryAPI/service", "Contact"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getContactRef"),
        "",
        "getContactRef",
        [ ["in", "DefinedValue_1", ["Etapper::DefinedValue", "etapestryAPI/service", "DefinedValue"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getDeclaration"),
        "",
        "getDeclaration",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Declaration", "etapestryAPI/service", "Declaration"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getDefinedField"),
        "",
        "getDefinedField",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::DefinedField", "etapestryAPI/service", "DefinedField"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getDefinedFields"),
        "",
        "getDefinedFields",
        [ ["in", "PagedDefinedFieldsRequest_1", ["Etapper::PagedDefinedFieldsRequest", "etapestryAPI/service", "PagedDefinedFieldsRequest"]],
        ["retval", "result", ["Etapper::PagedDefinedFieldsResponse", "etapestryAPI/service", "PagedDefinedFieldsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getDisbursement"),
        "",
        "getDisbursement",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Disbursement", "etapestryAPI/service", "Disbursement"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getDonorLoginPreferences"),
        "",
        "getDonorLoginPreferences",
        [ ["retval", "result", ["Etapper::DonorLoginPreferences", "etapestryAPI/service", "DonorLoginPreferences"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getDuplicateAccount"),
        "",
        "getDuplicateAccount",
        [ ["in", "DuplicateAccountSearch_1", ["Etapper::DuplicateAccountSearch", "etapestryAPI/service", "DuplicateAccountSearch"]],
        ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getDuplicateAccounts"),
        "",
        "getDuplicateAccounts",
        [ ["in", "DuplicateAccountSearch_1", ["Etapper::DuplicateAccountSearch", "etapestryAPI/service", "DuplicateAccountSearch"]],
        ["retval", "result", ["Etapper::ArrayOfAccount", "etapestryAPI/service", "ArrayOfAccount"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getDynamicQueryResults"),
        "",
        "getDynamicQueryResults",
        [ ["in", "PagedDynamicQueryResultsRequest_1", ["Etapper::PagedDynamicQueryResultsRequest", "etapestryAPI/service", "PagedDynamicQueryResultsRequest"]],
        ["retval", "result", ["Etapper::PagedQueryResultsResponse", "etapestryAPI/service", "PagedQueryResultsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getEntityRole"),
        "",
        "getEntityRole",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::EntityRole", "etapestryAPI/service", "EntityRole"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getExistingQueryResults"),
        "",
        "getExistingQueryResults",
        [ ["in", "PagedExistingQueryResultsRequest_1", ["Etapper::PagedExistingQueryResultsRequest", "etapestryAPI/service", "PagedExistingQueryResultsRequest"]],
        ["retval", "result", ["Etapper::PagedQueryResultsResponse", "etapestryAPI/service", "PagedQueryResultsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getFunds"),
        "",
        "getFunds",
        [ ["in", "boolean_1", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfstring", "etapestryAPI/service", "ArrayOfstring"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getGift"),
        "",
        "getGift",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Gift", "etapestryAPI/service", "Gift"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getInvitation"),
        "",
        "getInvitation",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Invitation", "etapestryAPI/service", "Invitation"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getJournalEntries"),
        "",
        "getJournalEntries",
        [ ["in", "PagedJournalEntriesRequest_1", ["Etapper::PagedJournalEntriesRequest", "etapestryAPI/service", "PagedJournalEntriesRequest"]],
        ["retval", "result", ["Etapper::PagedJournalEntriesResponse", "etapestryAPI/service", "PagedJournalEntriesResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getLetters"),
        "",
        "getLetters",
        [ ["in", "boolean_1", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfstring", "etapestryAPI/service", "ArrayOfstring"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getMyAccount"),
        "",
        "getMyAccount",
        [ ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getMyAccountByPersonaType"),
        "",
        "getMyAccountByPersonaType",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::Account", "etapestryAPI/service", "Account"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getMyEntityRole"),
        "",
        "getMyEntityRole",
        [ ["retval", "result", ["Etapper::EntityRole", "etapestryAPI/service", "EntityRole"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getMyJournalEntries"),
        "",
        "getMyJournalEntries",
        [ ["retval", "result", ["Etapper::Collection", "http://java.sun.com/jax-rpc-ri/internal", "collection"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getMyJournalSummary"),
        "",
        "getMyJournalSummary",
        [ ["retval", "result", ["Etapper::JournalSummary", "etapestryAPI/service", "JournalSummary"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getMyPrivacyPreferences"),
        "",
        "getMyPrivacyPreferences",
        [ ["retval", "result", ["Etapper::PrivacyPreferences", "etapestryAPI/service", "PrivacyPreferences"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getNextCartElements"),
        "",
        "getNextCartElements",
        [ ["retval", "result", ["Etapper::PagedCartElementsResponse", "etapestryAPI/service", "PagedCartElementsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getNextDefinedFields"),
        "",
        "getNextDefinedFields",
        [ ["retval", "result", ["Etapper::PagedDefinedFieldsResponse", "etapestryAPI/service", "PagedDefinedFieldsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getNextJournalEntries"),
        "",
        "getNextJournalEntries",
        [ ["retval", "result", ["Etapper::PagedJournalEntriesResponse", "etapestryAPI/service", "PagedJournalEntriesResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getNextQueryResults"),
        "",
        "getNextQueryResults",
        [ ["retval", "result", ["Etapper::PagedQueryResultsResponse", "etapestryAPI/service", "PagedQueryResultsResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getNote"),
        "",
        "getNote",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Note", "etapestryAPI/service", "Note"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getNoteByUniqueDefinedValue"),
        "",
        "getNoteByUniqueDefinedValue",
        [ ["in", "DefinedValue_1", ["Etapper::DefinedValue", "etapestryAPI/service", "DefinedValue"]],
        ["retval", "result", ["Etapper::Note", "etapestryAPI/service", "Note"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getNoteRef"),
        "",
        "getNoteRef",
        [ ["in", "DefinedValue_1", ["Etapper::DefinedValue", "etapestryAPI/service", "DefinedValue"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getOrderItem"),
        "",
        "getOrderItem",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::OrderItem", "etapestryAPI/service", "OrderItem"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getOrderShipping"),
        "",
        "getOrderShipping",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::OrderShipping", "etapestryAPI/service", "OrderShipping"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getOrderTax"),
        "",
        "getOrderTax",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::OrderTax", "etapestryAPI/service", "OrderTax"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getOrganizationPreferences"),
        "",
        "getOrganizationPreferences",
        [ ["retval", "result", ["Etapper::OrganizationPreferences", "etapestryAPI/service", "OrganizationPreferences"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getOutlookIntegrationContactMethods"),
        "",
        "getOutlookIntegrationContactMethods",
        [ ["retval", "result", ["Etapper::ArrayOfDefinedValue", "etapestryAPI/service", "ArrayOfDefinedValue"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getOutlookIntegrationVersion"),
        "",
        "getOutlookIntegrationVersion",
        [ ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getPayment"),
        "",
        "getPayment",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Payment", "etapestryAPI/service", "Payment"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getPhoneAThonLists"),
        "",
        "getPhoneAThonLists",
        [ ["in", "boolean_1", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfPhoneAThonList", "etapestryAPI/service", "ArrayOfPhoneAThonList"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getPledge"),
        "",
        "getPledge",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::Pledge", "etapestryAPI/service", "Pledge"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getPrivacyPreferences"),
        "",
        "getPrivacyPreferences",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::PrivacyPreferences", "etapestryAPI/service", "PrivacyPreferences"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getQueryResultStats"),
        "",
        "getQueryResultStats",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "String_2", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::QueryResultStats", "etapestryAPI/service", "QueryResultStats"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getRecurringGift"),
        "",
        "getRecurringGift",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::RecurringGift", "etapestryAPI/service", "RecurringGift"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getRecurringGiftSchedule"),
        "",
        "getRecurringGiftSchedule",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::RecurringGiftSchedule", "etapestryAPI/service", "RecurringGiftSchedule"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getSegmentedDonation"),
        "",
        "getSegmentedDonation",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::SegmentedDonation", "etapestryAPI/service", "SegmentedDonation"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getSegmentedOrder"),
        "",
        "getSegmentedOrder",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::SegmentedOrder", "etapestryAPI/service", "SegmentedOrder"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getSegmentedPledge"),
        "",
        "getSegmentedPledge",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::SegmentedPledge", "etapestryAPI/service", "SegmentedPledge"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getSoftCredit"),
        "",
        "getSoftCredit",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", ["Etapper::SoftCredit", "etapestryAPI/service", "SoftCredit"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getSystemDefinedValues"),
        "",
        "getSystemDefinedValues",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfDefinedValue", "etapestryAPI/service", "ArrayOfDefinedValue"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getTransaction"),
        "",
        "getTransaction",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["retval", "result", [nil]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getTransactionByUniqueDefinedValue"),
        "",
        "getTransactionByUniqueDefinedValue",
        [ ["in", "DefinedValue_1", ["Etapper::DefinedValue", "etapestryAPI/service", "DefinedValue"]],
        ["retval", "result", [nil]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getTransactionProcessors"),
        "",
        "getTransactionProcessors",
        [ ["in", "boolean_1", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfTransactionProcessor", "etapestryAPI/service", "ArrayOfTransactionProcessor"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getTransactionRef"),
        "",
        "getTransactionRef",
        [ ["in", "DefinedValue_1", ["Etapper::DefinedValue", "etapestryAPI/service", "DefinedValue"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "getUserDefinedSetValues"),
        "",
        "getUserDefinedSetValues",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["Etapper::ArrayOfDefinedValue", "etapestryAPI/service", "ArrayOfDefinedValue"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "hasMoreCartElements"),
        "",
        "hasMoreCartElements",
        [ ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "hasMoreDefinedFields"),
        "",
        "hasMoreDefinedFields",
        [ ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "hasMoreJournalEntries"),
        "",
        "hasMoreJournalEntries",
        [ ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "hasMoreQueryResults"),
        "",
        "hasMoreQueryResults",
        [ ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "initLinkedTransaction"),
        "",
        "initLinkedTransaction",
        [ ["retval", "result", ["Etapper::LinkedTransaction", "etapestryAPI/service", "LinkedTransaction"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "isMyPasswordExpired"),
        "",
        "isMyPasswordExpired",
        [ ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "login"),
        "",
        "login",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "String_2", ["::SOAP::SOAPString"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "logout"),
        "",
        "logout",
        [],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "pingOkay"),
        "",
        "pingOkay",
        [ ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "pingTime"),
        "",
        "pingTime",
        [ ["retval", "result", ["::SOAP::SOAPDateTime"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "processAccountChange"),
        "",
        "processAccountChange",
        [ ["in", "AccountChangeRequest_1", ["Etapper::AccountChangeRequest", "etapestryAPI/service", "AccountChangeRequest"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "processCartOrder"),
        "",
        "processCartOrder",
        [ ["in", "CartOrderRequest_1", ["Etapper::CartOrderRequest", "etapestryAPI/service", "CartOrderRequest"]],
        ["retval", "result", ["Etapper::CartOrderResponse", "etapestryAPI/service", "CartOrderResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "processEcommerceRequest"),
        "",
        "processEcommerceRequest",
        [ ["in", "EcommerceRequest_1", ["Etapper::EcommerceRequest", "etapestryAPI/service", "EcommerceRequest"]],
        ["retval", "result", ["Etapper::EcommerceResponse", "etapestryAPI/service", "EcommerceResponse"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "processForgottenPasswordEmailHelp"),
        "",
        "processForgottenPasswordEmailHelp",
        [ ["in", "ForgottenPasswordEmailHelpRequest_1", ["Etapper::ForgottenPasswordEmailHelpRequest", "etapestryAPI/service", "ForgottenPasswordEmailHelpRequest"]],
        ["retval", "result", ["::SOAP::SOAPInt"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "processForgottenPasswordResetHelp"),
        "",
        "processForgottenPasswordResetHelp",
        [ ["in", "ForgottenPasswordResetHelpRequest_1", ["Etapper::ForgottenPasswordResetHelpRequest", "etapestryAPI/service", "ForgottenPasswordResetHelpRequest"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "processTransaction"),
        "",
        "processTransaction",
        [ ["in", "ProcessTransactionRequest_1", ["Etapper::ProcessTransactionRequest", "etapestryAPI/service", "ProcessTransactionRequest"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "reverseTransaction"),
        "",
        "reverseTransaction",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "String_2", ["::SOAP::SOAPString"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "sendEmail"),
        "",
        "sendEmail",
        [ ["in", "SendEmailRequest_1", ["Etapper::SendEmailRequest", "etapestryAPI/service", "SendEmailRequest"]],
        ["retval", "result", ["::SOAP::SOAPInt"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updateAccount"),
        "",
        "updateAccount",
        [ ["in", "Account_1", ["Etapper::Account", "etapestryAPI/service", "Account"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updateContact"),
        "",
        "updateContact",
        [ ["in", "Contact_1", ["Etapper::Contact", "etapestryAPI/service", "Contact"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updateForgottenPassword"),
        "",
        "updateForgottenPassword",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "String_2", ["::SOAP::SOAPString"]],
        ["in", "String_3", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updateGift"),
        "",
        "updateGift",
        [ ["in", "Gift_1", ["Etapper::Gift", "etapestryAPI/service", "Gift"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updateMyExpiredPassword"),
        "",
        "updateMyExpiredPassword",
        [ ["in", "String_1", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updateMyLoginCredentials"),
        "",
        "updateMyLoginCredentials",
        [ ["in", "String_1", ["::SOAP::SOAPString"]],
        ["in", "String_2", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updateMyPassword"),
        "",
        "updateMyPassword",
        [ ["in", "String_1", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updateNote"),
        "",
        "updateNote",
        [ ["in", "Note_1", ["Etapper::Note", "etapestryAPI/service", "Note"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]],
        ["retval", "result", ["::SOAP::SOAPString"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "updatePrivacyPreferences"),
        "",
        "updatePrivacyPreferences",
        [ ["in", "PrivacyPreferences_1", ["Etapper::PrivacyPreferences", "etapestryAPI/service", "PrivacyPreferences"]],
        ["in", "boolean_2", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "validateCartLicense"),
        "",
        "validateCartLicense",
        [ ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "validateDonorLoginLicense"),
        "",
        "validateDonorLoginLicense",
        [ ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ],
      [ XSD::QName.new(NsService, "validateOutlookIntegrationLicense"),
        "",
        "validateOutlookIntegrationLicense",
        [ ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
        { :request_style =>  :rpc, :request_use =>  :encoded,
          :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
      ]
    ]
  end

end
